version: "2"
services:
  kong:
    restart: on-failure
    image: "kong:0.10"
    container_name: kong
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_HOST: database
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    security_opt:
      - label:seccomp:unconfined
    depends_on:
      - kong-database
  kong-database:
    image: "cassandra:2.2"
    container_name: kong-database
    ports:
      - 9042:9042
    volumes:
      - ./cassandra:/var/lib/cassandra
  kong-dashboard:
    restart: on-failure
    image: "pgbi/kong-dashboard:v2.0.0"
    container_name: kong-dashboard
    ports:
      - 8080:8080
    links:
      - kong:kong
    command: "npm start -- -a admin=tiki@1234"
